### ISSUE TITLE
Error while doing app export

### ISSUE THREAD

**Issue by dennajort** [MichaelMKenny/SunshineAppExport#1]
Hi ! I'm trying to use SunshineAppExport in order to export a game from epic games and there is this error.
<img width="559" alt="Screenshot 2023-01-23 203534" src="https://user-images.githubusercontent.com/1536838/214195356-202dea98-7f59-452d-ad3e-269a0e665211.png">
If I try to make it run again playnite crashes.
Thanks for looking into it !

**Comment by dennajort** [comment]
OK I think I made it working by installing the latest version of sunshine.

**Comment by MichaelMKenny** [comment]
Fixed in 1.1
