### ISSUE TITLE
[Request] Direct Command option

### ISSUE THREAD

**Issue by DenowRammy** [MichaelMKenny/SunshineAppExport#14]
Currently, this plugin just exports to sunshine with a `Playnite.DesktopApp.exe --start` detached command.

It'd be nice if there was the option to have the contents of the Playnite Action put into moonlight as a Command instead. The reason one would want this is, while it does get rid of goodies from playnite like startup scripts, gameactivity, etc, it would allow Sunshine to attach the game process and close when Moonlight send a quit command to Sunshine; something it cannot currently do.

Thanks!

**Comment by MichaelMKenny** [comment]
If you use this script: [PlayNiteWatcher](https://github.com/Nonary/PlayNiteWatcher), in combination with Sunshine App Export you'll get the best of both worlds
