### ISSUE TITLE
Repeat of #1 - Running exporter results in no exported apps

### ISSUE THREAD

**Issue by sylverpyro** [MichaelMKenny/SunshineAppExport#3]
Steps to reproduce:

1. Install latest Sunshine server and configure
2. Check apps.json (default contains just Desktop and Steam BigPicture)
3. Launch Playnite, highlight a game to export to Sunshine, select Extensions => Sunshine App Export
4. Select the default apps.json file (verified it exists and has the default applications)
5. Click Export
6. Dialogue returns 'success added 1 game'

Results:
1. The apps.json file is changed (the tab spacing mostly) showing that something was in fact written out
2. The apps.json file still only contains the two default apps
3. The newly exported game (app) does not show up in the apps.json file

Troubleshooting (that has not worked - I'm not quite good enough to run the debug shell)
1. Point the exporter at a dummy apps.json file on the desktop
  Result: Error message saying `Exception calling "ShowDialog" with "0" argument(s): "Cannot bind argument to parameter 'InputObject' because it is null'"`

Would LOVE to be able to bulk add applications to Sunshine.  Any debugging I can run, please let me know.

**Comment by MichaelMKenny** [comment]
Fixed in 1.1
