### ISSUE TITLE
File Path Error

### ISSUE THREAD

**Issue by WiseEXE** [MichaelMKenny/SunshineAppExport#4]
After using this tool to transfer my Playnite library over to Sunshine, I get an error stating that it cannot find my file directory. The issue is the directory it say is prompted for is incorrect because my Windows user has a space in it.

Example:
The current set-up for Metal Gear Rising:
![image](https://user-images.githubusercontent.com/105170549/227341143-23c3ca73-7104-43aa-b9b0-98454d25c639.png)

However when opening in Moonlight, I get streamed only my Desktop with this error
![image](https://user-images.githubusercontent.com/105170549/227340928-057ff761-bebf-4e02-b588-00194f4d8fe6.png)

**Comment by MichaelMKenny** [comment]
Ah, I probably need to add quotes around the command. My user is just “Michael”. Sorry about that.

**Comment by MichaelMKenny** [comment]
Fixed in 1.1
