### ISSUE TITLE
Sunshine 0.20 breaking changes

### ISSUE THREAD

**Issue by Nonary** [MichaelMKenny/SunshineAppExport#5]
Due to security issues, we've write locked the apps.json file to require administrator rights. So this plugin will not work unless PlayNite is running as administrator. It's a pretty easy fix as long as PlayNite allows requesting admin rights on plugins, but not sure what their policies are.

**Comment by MichaelMKenny** [comment]
Thanks for the heads up. 

Yeah, I'm not sure what Playnite's policy is with admin prompts, it might be not supported.

I might need to update the readme, for now.

**Comment by Nonary** [comment]
PR #6 fixes this, just waiting for the dev team on PlayNites discord to respond if they're okay with this.

**Comment by Nonary** [comment]
@MichaelMKenny Crowe, who is part of the PlayNite team said it was fine with them.
https://discord.com/channels/365863063296933888/894247902107545650/1113020909893193748

![image](https://github.com/MichaelMKenny/SunshineAppExport/assets/27069224/d53a2a78-e4c4-4680-9efa-b5e09d635522)

So feel free to review PR #6 and apply the changes, that will work with 0.20

**Comment by MichaelMKenny** [comment]
Fixed in 1.1
