### ISSUE TITLE
"Failed to Execute Menu Action"

### ISSUE THREAD

**Issue by KainHighwind5** [MichaelMKenny/SunshineAppExport#7]
Using the exporter I run into the following error (transcribing below in case the image doesn't attach)

Failed to execute menu action.

Exception calling "ShowDialog" with "0" argument(s): "Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'

let me know what info you need from me to troubleshoot this. thanks in advance!

![image](https://github.com/MichaelMKenny/SunshineAppExport/assets/105961322/131c89f1-a3aa-48d8-b308-65c28d3993e5)

**Comment by MichaelMKenny** [comment]
Fixed in 1.1
